### ISSUE TITLE
Bad quality of the image on iOS

### ISSUE THREAD

**Issue by Andrfas** [JimmyDaddy/react-native-image-marker#7]
I'm using `addTextByPostion` method, and it gives very bad quality of the image on iOS.
On Android it works good.
ReactNative version 0.49.3
![30922488-cb14-4668-bb9c-8f4be2676921](https://user-images.githubusercontent.com/3988369/35889066-af3dbae8-0ba2-11e8-9980-4c7197ef356a.jpg)

**Comment by sunkibaek** [comment]
@JimmyDaddy 

Might the line below be the reason?

https://github.com/JimmyDaddy/react-native-image-marker/blob/master/ios/RCTImageMarker/RCTImageMarker.m#L53

Since the documentation says that the quality is the amount between 0 and 1 and we are passing 0.1 effectively.

https://developer.apple.com/documentation/uikit/1624115-uiimagejpegrepresentation

**Comment by JimmyDaddy** [comment]
@sunkibaek thanks for your suggestion, I'll check this later and try to fix it

**Comment by richardkarsten** [comment]
It's definitely the line mentioned by @sunkibaek. Since I'am not a Objective C/native iOS developer I didn't find out, where the value of "quality" is defined or generated but I changed the line from 

`NSData* data = UIImageJPEGRepresentation(image, quality / 100.0);`
to
`NSData* data = UIImageJPEGRepresentation(image, 1.0);`

Result: 
![quality](https://user-images.githubusercontent.com/9954120/38361060-6941bdc6-38cc-11e8-97d5-176b8abb17f9.png)

_quality/100.0_ seems like there was planned a possibility to pass the quality to the function.

**Comment by JimmyDaddy** [comment]
The new version [`0.1.4`](https://www.npmjs.com/package/react-native-image-marker) fixed this problem, and I'll optimize the API to support pass quality at the next version

**Comment by Andrfas** [comment]
@JimmyDaddy thank you for the updates!

Sorry, but am I right that there are two more places to update the code from `1` to `100`?
https://github.com/JimmyDaddy/react-native-image-marker/blob/master/ios/RCTImageMarker/RCTImageMarker.m#L364
https://github.com/JimmyDaddy/react-native-image-marker/blob/master/ios/RCTImageMarker/RCTImageMarker.m#L409

Thanks!

**Comment by JimmyDaddy** [comment]
T_T, I'm sorry for this mistake, I'm too busy recently.
